### ISSUE TITLE
Windows can only take 3 minutes of video, how to record longer time

### ISSUE THREAD

**Issue by HandsomeTea** [131/screen-recorder#5]
Windows can only take 3 minutes of video, how to record longer time

**Comment by HandsomeTea** [comment]
Is it because of this in your code?
screenrecorder.js
`this._duration = 180;`

I think it is.

**Comment by HandsomeTea** [comment]
I changed the code I installed to a very large number.Minutes of a day
`this._duration = 86400;`
And then it worked.

**Comment by 131** [comment]
👍
